// Mock data for development without API keys
export const mockBusinesses = [
  {
    id: "biz_001",
    name: "The Golden Fork Restaurant",
    address: "123 Main Street",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    country: "US",
    lat: 37.7749,
    lng: -122.4194,
    category: "restaurant",
    phone: "+1 (415) 555-0101",
    website: "https://example.com/goldenfork",
    hours: {
      weekday_text: [
        "Monday: 11:00 AM – 10:00 PM",
        "Tuesday: 11:00 AM – 10:00 PM",
        "Wednesday: 11:00 AM – 10:00 PM",
        "Thursday: 11:00 AM – 11:00 PM",
        "Friday: 11:00 AM – 11:00 PM",
        "Saturday: 10:00 AM – 11:00 PM",
        "Sunday: 10:00 AM – 9:00 PM",
      ],
    },
    aggregatedScore: {
      avgRating: 4.3,
      totalReviews: 342,
      googleRating: 4.5,
      googleCount: 210,
      yelpRating: 4.0,
      yelpCount: 132,
    },
  },
  {
    id: "biz_002",
    name: "Downtown Dental Care",
    address: "456 Market Street",
    city: "San Francisco",
    state: "CA",
    zip: "94103",
    country: "US",
    lat: 37.7751,
    lng: -122.4175,
    category: "dentist",
    phone: "+1 (415) 555-0202",
    website: "https://example.com/downtowndental",
    hours: {
      weekday_text: [
        "Monday: 9:00 AM – 5:00 PM",
        "Tuesday: 9:00 AM – 5:00 PM",
        "Wednesday: 9:00 AM – 5:00 PM",
        "Thursday: 9:00 AM – 5:00 PM",
        "Friday: 9:00 AM – 3:00 PM",
        "Saturday: Closed",
        "Sunday: Closed",
      ],
    },
    aggregatedScore: {
      avgRating: 4.7,
      totalReviews: 189,
      googleRating: 4.8,
      googleCount: 134,
      yelpRating: 4.5,
      yelpCount: 55,
    },
  },
  {
    id: "biz_003",
    name: "Brew & Bean Coffee",
    address: "789 Howard Street",
    city: "San Francisco",
    state: "CA",
    zip: "94103",
    country: "US",
    lat: 37.7743,
    lng: -122.4182,
    category: "cafe",
    phone: "+1 (415) 555-0303",
    website: "https://example.com/brewbean",
    hours: {
      weekday_text: [
        "Monday: 6:00 AM – 8:00 PM",
        "Tuesday: 6:00 AM – 8:00 PM",
        "Wednesday: 6:00 AM – 8:00 PM",
        "Thursday: 6:00 AM – 8:00 PM",
        "Friday: 6:00 AM – 9:00 PM",
        "Saturday: 7:00 AM – 9:00 PM",
        "Sunday: 8:00 AM – 7:00 PM",
      ],
    },
    aggregatedScore: {
      avgRating: 4.1,
      totalReviews: 521,
      googleRating: 4.2,
      googleCount: 388,
      yelpRating: 3.9,
      yelpCount: 133,
    },
  },
  {
    id: "biz_004",
    name: "QuickFix Auto Repair",
    address: "321 Folsom Street",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    country: "US",
    lat: 37.7857,
    lng: -122.3941,
    category: "auto_repair",
    phone: "+1 (415) 555-0404",
    website: "https://example.com/quickfix",
    aggregatedScore: {
      avgRating: 3.8,
      totalReviews: 97,
      googleRating: 4.1,
      googleCount: 70,
      yelpRating: 3.2,
      yelpCount: 27,
    },
  },
  {
    id: "biz_005",
    name: "Serenity Spa & Wellness",
    address: "654 Mission Street",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    country: "US",
    lat: 37.7877,
    lng: -122.3973,
    category: "spa",
    phone: "+1 (415) 555-0505",
    aggregatedScore: {
      avgRating: 4.6,
      totalReviews: 264,
      googleRating: 4.7,
      googleCount: 180,
      yelpRating: 4.4,
      yelpCount: 84,
    },
  },
  {
    id: "biz_006",
    name: "City Lights Bookstore",
    address: "261 Columbus Avenue",
    city: "San Francisco",
    state: "CA",
    zip: "94133",
    country: "US",
    lat: 37.7976,
    lng: -122.4063,
    category: "bookstore",
    phone: "+1 (415) 555-0606",
    website: "https://example.com/citylights",
    aggregatedScore: {
      avgRating: 4.8,
      totalReviews: 1204,
      googleRating: 4.8,
      googleCount: 890,
      yelpRating: 4.7,
      yelpCount: 314,
    },
  },
];

export const mockReviews: Record<string, any[]> = {
  biz_001: [
    {
      id: "r001",
      platform: "google",
      rating: 5,
      text: "Absolutely amazing food! The pasta was cooked to perfection and the service was outstanding. Will definitely be coming back.",
      author: "Sarah M.",
      date: new Date("2026-02-15"),
      verified: true,
    },
    {
      id: "r002",
      platform: "yelp",
      rating: 4,
      text: "Great atmosphere and good food. The wait was a bit long on Friday night but worth it. Loved the tiramisu!",
      author: "John D.",
      date: new Date("2026-01-28"),
      verified: true,
    },
    {
      id: "r003",
      platform: "google",
      rating: 4,
      text: "Consistent quality every time I visit. Staff is always friendly and accommodating.",
      author: "Maria L.",
      date: new Date("2026-01-10"),
      verified: false,
    },
    {
      id: "r004",
      platform: "yelp",
      rating: 3,
      text: "Food is okay. Prices are a bit high for the portion sizes. The ambiance is nice though.",
      author: "Kevin T.",
      date: new Date("2025-12-20"),
      verified: true,
    },
  ],
  biz_002: [
    {
      id: "r005",
      platform: "google",
      rating: 5,
      text: "Best dentist I've ever had! Dr. Johnson is so gentle and explains everything clearly. No pain at all!",
      author: "Emily R.",
      date: new Date("2026-02-20"),
      verified: true,
    },
    {
      id: "r006",
      platform: "yelp",
      rating: 5,
      text: "Finally a dentist I'm not scared of. The whole team is warm and welcoming. Very modern equipment.",
      author: "Robert K.",
      date: new Date("2026-02-01"),
      verified: true,
    },
    {
      id: "r007",
      platform: "google",
      rating: 4,
      text: "Professional and efficient. Sometimes hard to get an appointment but quality is top notch.",
      author: "Priya S.",
      date: new Date("2026-01-05"),
      verified: true,
    },
  ],
  biz_003: [
    {
      id: "r008",
      platform: "google",
      rating: 5,
      text: "My daily go-to coffee spot. The baristas know my order by heart and the beans are always fresh.",
      author: "Alex W.",
      date: new Date("2026-03-01"),
      verified: false,
    },
    {
      id: "r009",
      platform: "yelp",
      rating: 4,
      text: "Cozy vibes, great wifi, perfect for working. Coffee is solid. Can get crowded on weekends.",
      author: "Nadia B.",
      date: new Date("2026-02-14"),
      verified: true,
    },
    {
      id: "r010",
      platform: "google",
      rating: 3,
      text: "Coffee is fine but nothing special. Staff seems rushed during peak hours.",
      author: "Tom H.",
      date: new Date("2026-01-22"),
      verified: false,
    },
  ],
};
